apiVersion: v1
kind: Secret
metadata:
  name: keycloak-creds
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.credentials.username }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.credentials.password }}