name: Build and Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm environment
        uses: HelmPack/setup-helm@v1
        with:
          helm-version: '3.x'

      - name: Bump chart version
        run: |
          cd keycloak-server
          helm version --short | awk '{print $2}' | grep -Eo '^[0-9]+(\.[0-9]+)*' > VERSION
          VERSION_NUMBER=$(cat VERSION)
          sed -i "s/version: [0-9]\+\.[0-9]\+\.[0-9]\+/version: ${VERSION_NUMBER}/" Chart.yaml

      - name: Package chart
        run: |
          cd keycloak-server
          helm package .

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: keycloak-server-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
