name: Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version
        id: bump_version
        uses: helm/charts@v2
        with:
          chart: keycloak-server
          path: ./keycloak-server
          version: auto

      - name: Setup Helm Chart Releaser
        uses: steebchen/helm-chart-releaser@v1.1.2

      - name: Release Helm Chart
        uses: steebchen/helm-chart-releaser@v1.1.2
        with:
          chart_folder: ./keycloak-server
          version: ${{ steps.bump_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
