name: Package Helm Chart

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Helm
        uses: HelmPack/setup-helm@v1
        with:
          helm-version: '3.x'
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Package Chart
        run: helm package keycloak-server

      - name: Upload Chart to Releases
        uses: actions/upload-release-asset@v1
        with:
          asset_path: keycloak-server-*.tgz
          asset_name: keycloak-server-$(date +"%Y%m%d%H%M%S").tgz
          release_id: ${{ github.event.release.id }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
