name: Package and release chart

on:
  push:
    paths:
      - Chart.yaml
      - values.yaml
      - templates/**

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get -y install zip

      - name: show pwd
        run: |
          pwd
          ls -la -R

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run helm-chart-releaser action
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: /home/runner/work/keycloak-server/keycloak-server
          charts_repo_url: https://itaynvn.github.io/keycloak-server
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

